<?php 

/*LOS NOMBRE DE LAS TABLAS QUE AFECTAN*/
define('TITULO',"Orden de Compra");  /*TITULO DEL LAS VISTAS */
define('TITULO2',"Compra"); /*TITULO DEL LAS VISTAS  DEL DOCUMENTO GENERADO*/
define('TITULO3',"Proveedor"); /*TITULO DEL LAS VISTAS  DEL DOCUMENTO GENERADO*/
define('TOTAL_A',"TOTAL A PAGAR"); /*TITULO DEL LAS VISTAS  DEL DOCUMENTO GENERADO*/
define('MODULO',"mod_compras"); /*PARA EL LINK DE LOS PROCESOS*/
define('MODULO2',"mod_proveedores"); /*PARA LA BUSQUEDA ASYNC DE LOS CLIENTES O PROVEEDORE*/
define('TABLA1',"compras"); /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA2',"compras_detalle"); /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA3',"inventario_movimientos");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA4',"cuenta_por_pagar");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA5',"inventario");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA6',"proveedores");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/

define('TIPO',"COMPRA");  /*TIPO DE DOCUMENTO EJEMPLO FACTURA, COMPRA, AJUSTE*/
define('SIGNO',"");  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/

define('AFECTA_MOVIMENTO_INVENTARIO',TRUE);  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/
define('AFECTA_CUENTA',TRUE);  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/

define('AFECTA_VENTAS',TRUE);  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/

?>

