<?php 

/*LOS NOMBRE DE LAS TABLAS QUE AFECTAN*/
define('TITULO',"Cuentas por pagar");  /*TITULO DEL LAS VISTAS */
 
define('MODULO',"mod_cuenta_por_pagar"); /*PARA LA BUSQUEDA ASYNC DE LOS CLIENTES O PROVEEDORE*/


define('TABLA',"cuenta_por_pagar"); /*PARA LA BUSQUEDA ASYNC Y PARA LOS ENVIE DE INFORMACION A LA BASE DE DATOS*/
define('TABLA2',"pagos"); /*PARA INSERTAR EN LA TABLA*/
define('TABLA3',"cajas_bancos_movimientos"); /*LA TABLA DE MOVIMIENTOS*/
define('TABLA5',"cajas_bancos"); /*ACTUALIZA EL SALDO EN*/
define('TIPO',"EGRESO"); /*PARA LA BUSQUEDA ASYNC DE LOS CLIENTES O PROVEEDORE*/
define('TIPO2',"COMPRA"); /*PARA LA BUSQUEDA ASYNC DE LOS CLIENTES O PROVEEDORE*/
define('SIGNO',"-"); /*PARA LA BUSQUEDA ASYNC DE LOS CLIENTES O PROVEEDORE*/
define('CAMBIASIGNO',-1); /*MENOS SI EN CXP*/
 

?>

