<?php 

/*LOS NOMBRE DE LAS TABLAS QUE AFECTAN*/
define('TITULO',"Salida de Inventario");  /*TITULO DEL LAS VISTAS */
define('TITULO2',"SAlida de Inventario"); /*TITULO DEL LAS VISTAS  DEL DOCUMENTO GENERADO*/
define('TITULO3',"empresa"); /*TITULO DEL LAS VISTAS  DEL DOCUMENTO GENERADO*/
define('TOTAL_A',"TOTAL"); /*TITULO DEL LAS VISTAS  DEL DOCUMENTO GENERADO*/
define('MODULO',"mod_articulos_salida"); /*PARA EL LINK DE LOS PROCESOS*/
define('MODULO2',"mod_empresa"); /*PARA LA BUSQUEDA ASYNC DE LOS CLIENTES O PROVEEDORE*/
define('TABLA1',"inventario_salida"); /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA2',"inventario_salida_detalle"); /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA3',"inventario_movimientos");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
/*define('TABLA4',"cuenta_por_cobrar");*/  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA5',"inventario");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/
define('TABLA6',"empresa");  /*LLAMADA DE TABLA EN EL ENVIO DE INFORMACION A LA BASE DE DATOS*/

define('TIPO',"AJUSTE SALIDA");  /*TIPO DE DOCUMENTO EJEMPLO FACTURA, COMPRA, AJUSTE*/
define('SIGNO',"-");  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/

define('AFECTA_MOVIMENTO_INVENTARIO',TRUE);  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/
define('AFECTA_CUENTA',FALSE);  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/

define('AFECTA_VENTAS',TRUE);  /*SIGNO QUE MODIFICA PARA LA ENTRADA DE CANTIDADES POSITIVO O NEGATIVO TABLA DE MOVIMIENTO DE INVENTARIO*/

?>

